### PR TITLE
Enh 12 add inotify

### LINKED ISSUE #12: Include inotify for use in odin-sequencer
The odin-sequencer recipe has been included without support for inotify (see #8), used to watch for changes in source files.

It would be better to include this in the build and edit the patch on odin-sequencer to no longer require removal of inotify from setup.py.

### PR DESCRIPTION
**Pull request by josephnobes-stfc**
Added git-based recipe for inotify to satisfy odin-sequencer requirement.

Closes #12

### CODE REVIEW

**Review by timcnicholls — COMMENTED** [review]
I noticed you are doing a direct install from the Git repo for inotify rather than using a pypi install?

**Comment by josephnobes-stfc** [comment]
Yes. I've tried using a pypi-based recipe, but it seems to insist on downloading a '1.0.0' version that doesn't exist, and so it fails. I have not been able to force it to the correct version, but if I did have to I think it would essentially be the same as what I'm doing with the git version.

This is the source referenced by pypi, and I've specified the latest tagged release as the version to use. Would it be better to try and push through using pypi instead?

**Comment by timcnicholls** [comment]
Ah OK I understand. No that's fine, stick with the git recipe if it's working 👍 

Be interesting to understand if/how the pypi recipe can pin a version. Just had a look at the bitbake class for it (`components/yocto/layers/core/meta/classes/pypi.bbclass`):

```
def pypi_package(d):
    bpn = d.getVar('BPN')
    if bpn.startswith('python-'):
        return bpn[7:]
    elif bpn.startswith('python3-'):
        return bpn[8:]
    return bpn

PYPI_PACKAGE ?= "${@pypi_package(d)}"
PYPI_PACKAGE_EXT ?= "tar.gz"

def pypi_src_uri(d):
    package = d.getVar('PYPI_PACKAGE')
    package_ext = d.getVar('PYPI_PACKAGE_EXT')
    pv = d.getVar('PV')
    return 'https://files.pythonhosted.org/packages/source/%s/%s/%s-%s.%s' % (package[0], package, package, pv, package_ext)

PYPI_SRC_URI ?= "${@pypi_src_uri(d)}"

HOMEPAGE ?= "https://pypi.python.org/pypi/${PYPI_PACKAGE}/"
SECTION = "devel/python"
SRC_URI += "${PYPI_SRC_URI}"
S = "${WORKDIR}/${PYPI_PACKAGE}-${PV}"

UPSTREAM_CHECK_URI ?= "https://pypi.python.org/pypi/${PYPI_PACKAGE}/"
UPSTREAM_CHECK_REGEX ?= "/${PYPI_PACKAGE}/(?P<pver>(\d+[\.\-_]*)+)"
```

Maybe setting the PV variable to 0.2.10 in a pypi recipe would force it to retrieve that version?

**Comment by josephnobes-stfc** [comment]
I've been able to get the pypi version to work after removing a few more parts of the recipe that were overriding and causing it to fail (it would have been better just to create it from scratch!).

It is essentially the same, though the license check has to be removed because the pypi source does not include the file for some reason.

**Comment by timcnicholls** [comment]
Nice work! Another bit of petalinux/bitbake knowledge gained 👍

**Comment by josephnobes-stfc** [comment]
Pypi-based recipe has now been added for consistency.
Because license is not present in the pypi-distributed version, it must be specified as LICENSE = "CLOSED" in the recipe to pass license checks in BitBake.

**Comment by josephnobes-stfc** [comment]
It appears that whether the license is included in the package is down to the files in the inotify repository. The LICENSE file should be specified somewhere in setup.cfg or MANIFEST.in (or possibly somewhere else) to appear in the source distribution.

We will just need to be mindful that for future recipes the .tar.gz version of the source from Pypi should be checked for license rather than the latest on GH for the recipe to compile.

**Review by timcnicholls — APPROVED** [review]

**Pull request merged**
